READMEs
esl/MongooseHelm pull request #6
Opened 2020-11-25 20:48 UTC by NelsonVides

WIP PR, so far commits can be followed one by one, there are several things happening but I've tried to prepare a readable history for it.

2020-11-30 14:04 UTC, DenysGonchar commented on MongooseIM/README.md
> +| `loadBalancerIP`   | Exposed external IP address for the Load Balancer    | not set (will be automatically assigned) |
that would be nice to mention that it's XMPP TCP interface

2020-11-30 14:15 UTC, DenysGonchar commented on README.md
> +  * [How to recover the plain k8s files](#how-to-recover-the-plain-k8s-files)
why `recover`? we haven't broken them :) i would say `how to get the plain...`

2020-11-30 14:20 UTC, DenysGonchar commented on README.md
> +kubectl config use-context docker-desktop  # if Docker Desktop with Kubernetes is enabled
`if Docker Desktop with Kubernetes is enabled` -  it sounds weird, can we rephrase it?

2020-11-30 14:26 UTC, DenysGonchar requested changes
Please add links to the MIM and MongoosePush charts' READMEs to the main README file of the repo

2020-11-30 14:28 UTC, DenysGonchar commented on README.md
> +kubectl config use-context docker-desktop  # if Docker Desktop with Kubernetes is enabled
overall, all the READMEs look nice and informative. thanks a lot for the changes.

2020-11-30 14:30 UTC, DenysGonchar commented
overall, all the READMEs look nice and informative. thanks a lot for the changes.

2020-11-30 15:08 UTC, DenysGonchar approved these changes

2020-12-01 08:46 UTC, chrzaszcz reviewed
I tried to follow the steps and encountered a few issues, could you take a look?

2020-12-01 08:46 UTC, chrzaszcz commented on MongooseIM/README.md
> +| `nodeName`         | Name of the nodes as containers                      | `mongooseim` |
This has no effect - `start.sh` just overwrites it.

2020-12-01 08:46 UTC, chrzaszcz commented on MongooseIM/README.md
> +| `mimConfig`        | User-given `mongooseim.toml` configuration file      | not set (internal default, check sources) |
I would somehow underline that this is the main MongooseIM config file while `vm.args` is for tweaking the Erlang VM itself, so usually only `mongooseim.toml` needs to be provided.

2020-12-01 08:46 UTC, chrzaszcz commented on MongooseIM/README.md
> +$ kubectl exec mongoose-0 /usr/lib/mongooseim/bin/mongooseimctl mnesia running_db_nodes
There's no pod `mongoose-0` here, it's `mongooseim-0`, btw I could not get them to cluster, I am not sure why.

2020-12-01 08:46 UTC, chrzaszcz commented on MongooseIM/README.md
> +helm upgrade mim MongooseIM --set nodeport.enabled=true
Previous `upgrade` exaple used `mongoose/mongooseim` but this one uses `MongooseIM` - is this on purpose? I think the user might get a bit lost and not understand that we moved to the cloned-repo version here.

2020-12-01 13:28 UTC, NelsonVides commented on MongooseIM/README.md
> +$ kubectl exec mongoose-0 /usr/lib/mongooseim/bin/mongooseimctl mnesia running_db_nodes
Name fixed, here and in other places I missed. Like, the very `mongoose-svc.yaml` that defines the clustering logic, a very long time ago I forgot to update the name of the app there!

2020-12-01 16:00 UTC, chrzaszcz approved these changes
All systems go now, checked. Great work!

2020-12-01 17:07 UTC, merged